# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class Action(BaseModel):
    card_index: typing.Optional[int] = None

class CardInfo(BaseModel):
    card: typing.Optional[str] = Field(default=None, description='Card in format: value suit')

class GameState(BaseModel):
    hand: typing.List[str] = Field(description='Your cards')
    briscola: typing.Optional[str] = Field(default=None, description='Trump suit')
    played: typing.List[str] = Field(description='All played cards')
    opponent_card: typing.Optional[str] = Field(default=None, description='Card opponent just played (if any)')

class SimpleAction(BaseModel):
    card_index: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
