# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Action": types.Action,
    "stream_types.Action": stream_types.Action,

    "types.CardInfo": types.CardInfo,
    "stream_types.CardInfo": stream_types.CardInfo,

    "types.GameState": types.GameState,
    "stream_types.GameState": stream_types.GameState,

    "types.SimpleAction": types.SimpleAction,
    "stream_types.SimpleAction": stream_types.SimpleAction,


}